edition = "2018"
max_width = 120
merge_imports = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
